### ISSUE TITLE
hi fahad

### ISSUE THREAD

**Issue by fahad4x4** [fa16np/Yo-FilesOrganizer-Linux#1]
hi fahad 
Is it possible to organize all files even within subfolders

**Comment by fa16np** [comment]
This script does not have it but you can go to each folder and run it.
Or you can download other version 
(

https://github.com/fa16np/Yo-FilesOrganizer-Windows-Mac

Needs java installed.
)

and do it, it has the feature but only case it wont work in linux is with files without names.

**Comment by fahad4x4** [comment]
Thank you I will try it
